### PR TITLE
first pass at hook, update language of models

### PR DESCRIPTION
**Pull request by anjiemerchant**
hi @clacla826 and @annabelnlau , 

i spent some time yesterday working on a hook that will update the availability of a service based on the status of an agreement. it's almost working... i also changed some of the model language to make it a little bit more clear who is the requestor and who is the requestee. lastly, i moved the seed file into "scripts" and changed the package.json to reference its new location. please take a look at let me know if you have any questions. 

thanks,
anjali

### CODE REVIEW

**Review by clacla826 — COMMENTED** [review]
Thanks @anjiemerchant! I see that there's a merge conflict to resolve... can you resolve it locally and maybe push again?

**Comment by anjiemerchant** [comment]
hi @clacla826 and @annabelnlau  (cc @k-vosswinkel ), i want to make sure you're okay with the changes i made before i resolve the conflicts locally. if you can review the files/changes and give the go-ahead, i will do so.

thanks!

**Comment by clacla826** [comment]
Hey @anjiemerchant, they look great to me! Thanks!

**Comment by annabelnlau** [comment]
@anjiemerchant It looks good to me! FYI, in an earlier version, we changed `node-modules` in the gitignore to `node_modules` so that they don't get pushed to github. That's an easy fix. Everything else looks great.

**Comment by anjiemerchant** [comment]
@annabelnlau and @clacla826 , merge conflicts are fixed. it's ready to merge

**Review by annabelnlau — COMMENTED** [review]
Wow, you even wrote tests. Great job!

**Pull request merged**
